HeyM8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req:redirect('feed:feed', section='tan') if req.user.is_authenticated else redirect('/users/signin')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('communities/', include('communities.urls')),
    path('feed/', include('feed.urls')),
    path('complaint/', include('complaint.urls')),
    path('meetmate/', include('MeetMate.urls')),
    path('ratemate/', include('RateMate.urls')),
    path('chats/', include('chat.urls'))
]

chat/urls.py
from django.urls import path

app_name = 'chat'
urlpatterns = [

]

users/urls.py
from django.urls import path
from . import views

app_name="users"
urlpatterns = [
    path('signin', views.SignInAndUp, name="signInAndUp"),
    path('logout', views.Logout, name="logout"),
    path('intro', views.Intro, name="intro"),
    path('albums/<str:albumID>', views.AlbumPictures, name="albumPictures"),
    path('user/<str:uniqueURL>', views.UserPage, name="userPage"),
    path('settings/<str:section>', views.Settings, name='settings'),
    path('editStatus', views.EditStatus, name='editStatus'),
    path('newThought', views.NewThought, name='newThought'),

    path('confirm/<uuid:confirmationKey>', views.ConfirmEmail),
]

templates/core/base_User_Interface_PC.html
{% extends "core/core_template_PC.html" %}
{% comment %} 
    all links to css and js are defined in this file
    lmRef for left menu links' styles and js
    rmRef for right menu link's styles
    rmGetRef for right menu link's js(links which just open another section on the same page)
    externalRef for right menu link's js(links which redirect to another page)
    content and rightMenu are containers for content and right menu respectively
{% endcomment %}
{% block customStyles %}
    <link rel="stylesheet" type="text/css" href="{% static 'core/core_uinterface_style_PC.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'feed/css/feed_style_PC.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/user_page_style_PC.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'communities/css/communities_style_PC.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'chat/css/chat_style_PC.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/settings_style_PC.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/albums_style_PC.css'%} ">
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/album_Pictures_style_PC.css' %}">
{% endblock customStyles %}

{% block customJS %}
    <script src="{% static 'core/core_uinterface_JS_PC.js' %}"></script>
    <script src="{% static 'feed/js/feed_JS_PC.js' %}"></script>
    <script src="{% static 'users/js/user_page_JS_PC.js' %}"></script>
    <script src="{% static 'communities/js/communities_JS_PC.js' %}"></script>
    <script src="{% static 'chat/js/chat_JS_PC.js' %}"></script>
    <script src="{% static 'users/js/settings_JS_PC.js' %}"></script>
{% endblock customJS %}

{% block pageContent %}
    <div id="leftMenu">
        {% block leftMenu %}
            <ul class="lm">

                <li id="logo-container">
                    <a href="/" id="logo">HeyM8</a>
                </li>

                <li class="lm-item">
                    <a class="lmRef fullAjaxRef" id="self" href="{% url 'users:userPage' uniqueURL %}">My page</a>
                </li>

                <li class="lm-item">
                    <a class="lmRef fullAjaxRef" id="feed" href="{% url 'feed:feed' 'tan' %}">Thoughts&News</a>
                </li>

                <li class="lm-item">
                    <a class="lmRef fullAjaxRef" id="chat" href="#">Chat</a>
                </li>

                <li class="lm-item">
                    <a class="lmRef fullAjaxRef" id="mates" href="#">Mates</a>
                </li>

                <li class="lm-item">
                    <a class="lmRef fullAjaxRef" id="communities" href="#">Communities</a>
                </li>

                <li class="lm-item">
                    <a class="lmRef fullAjaxRef" id="favourite" href="#">Favourite</a>
                </li>

                <li class="lm-item">
                    <a class="lmRef fullAjaxRef" id="settings" href="{% url 'users:settings' 'pi' %}">Settings</a>
                </li>

                <li class="lm-item">
                    <a class="lmRef fullAjaxRef" id="logout" href="{% url 'users:logout' %}">Log out</a>
                </li>
                
            </ul>  
        {% endblock leftMenu %}
    </div>
    
    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>

    <div id="rightMenu">
        {% block rightMenu %}
        {% endblock rightMenu %}
    </div>
{% endblock pageContent %}

templates/core/core_template_PC.html
<!DOCTYPE html>

{% block htmlLanguage %}
<html lang="en"></html>
{% endblock htmlLanguage %}

<head>  
    <meta name="description" content="Modern way to meet new people and get new emotions." />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    {% block customMeta %}
    {% endblock customMeta %}

    {% block coreStyle %}
    <link rel="shortcut icon" href="{% static 'core/H8_icon.ico' %}" />
    <link rel="stylesheet" href="{% static 'bootstrap-4/css/bootstrap.min.css' %}">        
    <link rel="stylesheet" href="{% static 'core/core_style_PC.css' %}"> 
    {% endblock coreStyle %} 

    {% block customStyles %}
    {% endblock customStyles %}

    {% block pageTitle %}
    <title>HeyM8</title>
    {% endblock pageTitle %} 

</head>
<body>

    <div id="pageContent">
        {% block pageContent %}
        {% endblock pageContent %}
    </div>

    {% block coreJS %}
    <script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'jquery-visible/jquery.visible.min.js' %}"></script>    
    <script src="{% static 'popper/popper.min.js' %}"></script>
    <script src="{% static 'fontawesome/js/all.js' %}"></script>
    <script src="{% static 'bootstrap-4/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'core/core_JS_PC.js' %}"></script>
    {% endblock coreJS %}

    {% block customJS %}
    {% endblock customJS %}

</body>
</html>