HeyM8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req:redirect('feed:feed', section='tan') if req.user.is_authenticated else redirect('/users/signin')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('communities/', include('communities.urls')),
    path('feed/', include('feed.urls')),
    path('complaint/', include('complaint.urls')),
    path('meetmate/', include('MeetMate.urls')),
    path('ratemate/', include('RateMate.urls')),
    path('chats/', include('chat.urls'))
]

chat/urls.py
from django.urls import path

app_name = 'chat'
urlpatterns = [

]

users/urls.py
from django.urls import path
from . import views

app_name="users"
urlpatterns = [
    path('signin', views.SignInAndUp, name="signInAndUp"),
    path('logout', views.Logout, name="logout"),
    path('intro', views.Intro, name="intro"),
    path('albums/<str:albumID>', views.AlbumPictures, name="albumPictures"),
    path('user/<str:uniqueURL>', views.UserPage, name="userPage"),
    path('settings/<str:section>', views.Settings, name='settings'),
    path('editStatus', views.EditStatus, name='editStatus'),
    path('newThought', views.NewThought, name='newThought'),

    path('confirm/<uuid:confirmationKey>', views.ConfirmEmail),
]

users/models.py
import datetime
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils.translation import gettext_lazy as _
from HeyM8.settings import AUTH_USER_MODEL
from . import choices 
from HeyM8.models import Note, BreakingHistory
from django.utils import timezone
from django.contrib.auth.validators import UnicodeUsernameValidator


class User(AbstractUser):#core User model
    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        abstract=False

    email = models.EmailField(
        _('email address'), 
        unique=True,
        error_messages={'unique': _("A user with that username already exists."),},
        )#unique field

    username = models.CharField(
        _('username'),
        max_length=30,
    )#override to reduce max_len and remove unique option

    uniqueURL = models.CharField(
        max_length=25,
        unique=True,
        blank=True,
        null=True,
    )#when accessing https://HeyM8.com/user/{{uniqueURL}} show user's page, 
    #first uniqueURL=id
    #can't be entirely numeric

    USERNAME_FIELD = 'email'#unique field

    REQUIRED_FIELDS = ['username']#required fields

    isDeleted = models.BooleanField(
        default=False,
    )#indicates whether this account is deleted/instaed of deleting account set this field to True

    isBanned = models.BooleanField(
        default=False,
    )#indicates whether this user is banned

    bannedTill = models.DateField(
        null=True,
    )#if user is banned specifies the date when he is unbanned

    finalRating = models.FloatField(
        default=0.0,
    )#final user's rating based on his rating(RateMate)

    mateList = models.ManyToManyField(
        AUTH_USER_MODEL, 
        related_name="mates"
    )#users added by this user

    sentReqs = models.ManyToManyField(
        AUTH_USER_MODEL,
        related_name="received_Reqs"
    )#user to which this user has sent add request

    communitiesList = models.ManyToManyField(
        "communities.Community", 
        related_name="members"
    )#communities which user has entolled 

    lastSeen = models.DateTimeField(
        "was online for the last time",
        default=timezone.now,
    )#when user was online for the last time

    def __str__(self):
        return "Username: {}, email: {}".format(self.username, self.email)

    def get_short_name(self):#overrides AbstractUser's function because this model has no name and second_name
        return self.username


class StatisticInfo(models.Model):#user's statistics

    class Meta:
        verbose_name = 'statisticInfo'
        verbose_name_plural = 'statisticInfos'

    user = models.OneToOneField(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="statistic_Info"
    )

    confirmationKey = models.UUIDField(
        "key to redirect in email",
        null=True,
    )#key to redirect in email

    isActive = models.BooleanField(
        default=True,
    )#indicates whether user actively uses service (whether he can be found via MeetMate)

    nOfReceivedSpamComplaints = models.IntegerField(
        default=0,
    )#number of received spam complaints

    usedMeetMate = models.BooleanField(
        default=False,
    )#indicates if user has ever foud mate using MeetMate

    usedRateMate = models.BooleanField(
        default=False,
    )#indicates if user has ever foud mate using RateMate


class PersonalInfo(models.Model):#user's pesonal info

    class Meta:
        verbose_name = 'personalInfo'
        verbose_name_plural = 'personalInfos'

    user = models.OneToOneField(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="personal_Info",
    )#user this info belongs to

    status = models.CharField(
        _('status'),
        max_length=200,
        null=True,
        blank=True, 
    )#override to reduce max_len and remove unique option

    fttd = ArrayField(
        models.CharField(
            max_length=40,
            choices=choices.FAVORITE_THEMES_TO_DISCUSS_CHOICES,
            ),
        null=True, 
        blank=True,
    )#favorite themes to discuss

    fa = ArrayField(
        models.CharField(
            max_length=40,
            choices=choices.FAVORITE_ACTIVITIES_CHOICES,
            ), 
        size=3,
        null=True, 
        blank=True,
    )#favorite activities

    lp = ArrayField(
        models.CharField(
            max_length=40,
            choices=choices.LIFE_PRIORITIES_CHOICES,
            ), 
        null=True, 
        blank=True,
        size=3,
    )#life priorities

    mvpq = ArrayField(
        models.CharField(
            max_length=40,
            choices=choices.MOST_VALUABLE_PERSONAL_QUALITIES_CHOICES,
            ), 
        null=True, 
        blank=True,
        size=3,
    )#most valuable personal qualities

    languages = ArrayField(
        models.CharField(
            max_length=7,
        ),
        null=True,
        blank=True,
    )#languages user knows

    gender = models.CharField(
        max_length=1,
        null=True, 
        blank=True,
        default='n',
    )#user's gender

    dob = models.DateField(
        "Date of birth",
        null=True,
        blank=True
    )#date of birth

    age = models.IntegerField(
        "Age",
        null=True,
        blank=True
    )#age


class UserSettings(models.Model):#defines user's settings for account

    class Meta:
        verbose_name = 'userSettings'
        verbose_name_plural = 'userSettings'

    mainPicture = models.ForeignKey(
        'users.UserPicture',
        on_delete=models.CASCADE,
        related_name='main_For',
        null=True,
    )

    user = models.OneToOneField(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="settings",
    )#user these settings belong to 

    blockedUsers = models.ManyToManyField(
        AUTH_USER_MODEL, 
        related_name="blocked_By",
    )#list of users blocked by this user

    isOpenForNewAcquaintances = models.BooleanField(
        default=True
    )#if True he will be able to use MeetMate accessible via MeetMate

    whoCanSeeMyGeoLocation = models.CharField(
        max_length=6,
    )#who can see country and city 

    whoCanSeeMyAlbums = models.CharField(
        max_length = 6,
        default="all",
    )#everyone can see profile pitcure but user can define who can see other pics


class UserBreakingHistory(BreakingHistory):#responsible for gathering info about user's rule breaking

    class Meta:
        verbose_name = 'UserBreakingHistory'
        verbose_name_plural = 'UserBreakingHistories'
    
    user = models.OneToOneField(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="breaking_History"
    )#user this history belongs to

    thoughUserWasBannedFor = models.ForeignKey(
        "users.Thought",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="thought_User_Was_Banned_For"
    )#if user is banned this thought is shown to him when he tries to login

    nOfSpamComplaints = models.IntegerField(default=0)#how many spam complaints user has received

    lastTimeUserGotSpamComplaint = models.DateField(null=True)#after 1 month of not getting spam complaints nOfSpamComplaints becomes 0 

    nOfSpamBreakings = models.IntegerField(default=0)#how many times user has broken spam rule


class UserAlbum(models.Model):
    
    name = models.CharField(
        max_length=35,
    )#album's name

    description = models.CharField(
        max_length=100,
        null=True,
    )#album's description

    custom = models.BooleanField(
        default=True,
    )#all pictures and thought pictures can not be deleted

    user = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='albums',
    )#user it belongs to

    mainPicture = models.ForeignKey(
        "users.UserPicture",
        on_delete=models.SET_NULL,
        null=True,
        related_name='album_Main_For',
    )#picture which is "face" of the album


class UserPicture(models.Model):

    album = models.ForeignKey(
        "users.UserAlbum",
        on_delete=models.CASCADE,
        related_name="pictures"
    )#album it belongs to

    uploadTime = models.DateTimeField(
        default=timezone.now,
    )#when picture was uploaded    

    picture = models.ImageField(
        upload_to="pics"
    )#picture itself


class Thought(Note):#core value unit created by user
    
    class Meta:
        verbose_name = 'thought'
        verbose_name_plural = 'thoughts'

    user = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="thoughts",
    )#user this thought belongs to

    pictures = models.ManyToManyField(
        'users.UserPicture',
        related_name="attached_To"
    )#picturse attached to the thought

users/forms.py
from django import forms


class SignUpForm(forms.Form):

    username = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':"Username"
            }
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class':'form-control',
                'placeholder':'Email',
            }
        )
    )

    password = forms.CharField(
        max_length=128, 
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'placeholder':'Password'
            }
        ), 
    )


class SignInForm(forms.Form):

    Email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class':'form-control',
                'placeholder':'Email',
            }
        )
    )

    Password = forms.CharField(
        max_length=128, 
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'placeholder':'Password'
            }
        ), 
    )

    RememberMe = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'checked':True,
            }
        )
    )

templates/users/intro_PC.html
{% extends "core/core_template_PC.html" %} 

{% block customStyles %}
    <link rel="stylesheet" href="{% static 'users/css/intro_style_PC.css' %}">
{% endblock customStyles %}

{% block pageContent %}
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3 center-text">Modern way to meet new people and get new emotions!</h1>
        </div>
    </div>
    <div id="container" class="content">
        <div class="texxxt">
            <h1 class="header center-text">General information</h1>
            <h2 class="center-text"><span class="question">What is HeyM8?</h2></span><p>HeyMate is a platform for making new friends.</p>
        </div>
    </div>
{% endblock pageContent %}

templates/users/settings_PC.html
{% extends "core/base_User_Interface_PC.html" %}

{% block content %}
    {% include "users/content/settings_content_PC.html" %}
{% endblock content %}

{% block rightMenu %}
    {% include "users/rm/settings_rm_PC.html" %}
{% endblock rightMenu %}

templates/users/signInAndUp_PC.html
{% extends "core/core_template_PC.html" %}

{% block customMeta %}
{% endblock customMeta %}

{% block customStyles %}
    <link rel="stylesheet" type="text/css" href="{% static 'users/css/signInAndUp_style_PC.css' %}">
{% endblock customStyles %}

{% block customJS %}
    <script src="{% static 'users/js/signInAndUp_JS_PC.js' %}"></script>
{% endblock customJS %}

{% block pageTitle %}
    <title>Sign in</title>
{% endblock pageTitle %}

{% block pageContent %} 
    <div id="logo">
        <div class="jumbotron text-center">
            <h1><a href="/">HeyM8</a></h1>
            <p>Modern way to meet new people and get new emotions.</p>
        </div>
    </div>
    <div class="enteringForms">
        <div class="signIn">
            <h2>Sign in</h2>
            <form class="signInForm" action="{% url 'users:signInAndUp' %}" method="POST"> 
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_Email">Email:</label>
                    {{ signInForm.Email }}
                </div>
                <div class="form-group">
                    <label for="id_Password">Password:</label>
                    {{ signInForm.Password }}
                </div>
                <div class="checkbox">
                    <label>{{ signInForm.RememberMe }}Remember me</label>
                </div>
                <input type="submit" value="Sign in" class="btn btn-default" id="submitSignIn">
            </form>
            <p class="notice" id="signInNotice"></p>
            <div class="sk-fading-circle" id="in-preloader">
                <div class="sk-circle1 sk-circle"></div>
                <div class="sk-circle2 sk-circle"></div>
                <div class="sk-circle3 sk-circle"></div>
                <div class="sk-circle4 sk-circle"></div>
                <div class="sk-circle5 sk-circle"></div>
                <div class="sk-circle6 sk-circle"></div>
                <div class="sk-circle7 sk-circle"></div>
                <div class="sk-circle8 sk-circle"></div>
                <div class="sk-circle9 sk-circle"></div>
                <div class="sk-circle10 sk-circle"></div>
                <div class="sk-circle11 sk-circle"></div>
                <div class="sk-circle12 sk-circle"></div>
            </div>
        </div><!-- signIn -->
        <div class="signUp">
            <h2>Sign up</h2>
            <form class="signUpForm" action="{% url 'users:signInAndUp' %}" method="POST"> 
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">Username:</label>
                    {{ signUpForm.username }}
                </div>
                <div class="form-group">
                    <label for="id_email">Email:</label>
                    {{ signUpForm.email }}
                </div>
                <div class="form-group">
                    <label for="id_password">Password:</label>
                    {{ signUpForm.password }}
                </div>
                <input type="submit" value="Sign up" class="btn btn-default" id="submitSignUp">
            </form>
            <p class="notice" id="signUpNotice"></p>
            <div class="sk-fading-circle" id="up-preloader">
                <div class="sk-circle1 sk-circle"></div>
                <div class="sk-circle2 sk-circle"></div>
                <div class="sk-circle3 sk-circle"></div>
                <div class="sk-circle4 sk-circle"></div>
                <div class="sk-circle5 sk-circle"></div>
                <div class="sk-circle6 sk-circle"></div>
                <div class="sk-circle7 sk-circle"></div>
                <div class="sk-circle8 sk-circle"></div>
                <div class="sk-circle9 sk-circle"></div>
                <div class="sk-circle10 sk-circle"></div>
                <div class="sk-circle11 sk-circle"></div>
                <div class="sk-circle12 sk-circle"></div>
            </div>
        </div><!-- signUp -->
    </div><!-- enteringForms -->
{% endblock pageContent %}

templates/users/user_Page_PC.html
{% extends "core/base_User_Interface_PC.html" %}

{% block content %}
    {% include "users/content/user_Page_content_PC.html" %}
{% endblock content %}

{% block rightMenu %}
    {% include "users/rm/user_Page_rm_PC.html" %}
{% endblock rightMenu %}